server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/notification-db
    username: rulik
    password: qwerty123
  flyway:
    enabled: true
    locations: classpath:/db/migration
  kafka:
    bootstrap-servers: localhost:9092