services:
  author-db:
    image: postgres:15-alpine
    container_name: author-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rulik
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: author-db
    volumes:
      - author-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - book-api-network
  book-db:
    image: postgres:15-alpine
    container_name: book-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rulik
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: book-db
    volumes:
      - book-db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - book-api-network
  notification-db:
    image: postgres:15-alpine
    container_name: notification-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rulik
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: notification-db
    volumes:
      - notification-db:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - book-api-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: book-api-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: book-api-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network

volumes:
  author-db:
  book-db:
  notification-db:

networks:
  book-api-network:
    driver: bridge
  kafka-network:
    driver: bridge