server:
  port: 8082

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/book-db
    username: rulik
    password: qwerty123
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true